// console.log("Hello JS");

// const a=12;
// if(a>10){
//     let b=23;
//     a=40;
//     console.log("a="+a);
// }
// console.log("Hi, a="+b);

// function fun(){
//     console.log("Heeee");
// }
// fun();

// function fun(a,b,c=1){
//     console.log("heee")
//     return a+b+c;
// }
// let data=fun(2,4);
// console.log(data);




// function selectlanguage(language) {
//     let data;
//     if (language == 'c') {
//         function cCompiler() {
//             return "C Compiler";
//         }
//         data = cCompiler();
//     }
//     if (language == "java") {
//         function javaCompiler() {
//             return "Java Compiler";
//         }
//         data=javaCompiler();
//     }
//     return data;


// }
// const result = selectlanguage("java");
// console.log(result);
// console.log(document);



// console.dir(document);
// const div=document.getElementsByClassName("parent");
// console.dir(div);
// div[0].innerHTML="<h2>ABES Engineering College</h2>";
// const h1=document.createElement("h1");
// h1.innerText="This is generated by DOM";
// h1.style.backgroundColor='cyan';
// console.log(h1);
// div[0].appendChild(h1);
// const img=document.createElement('img');
// img.src='./download.jpeg';
// console.log(img);
// div[0].appendChild(img);


// const disp=document.getElementById("disp");
// console.dir(disp);
// function getData(){
//     console.log("Getdata called");
//     disp.innerHTML="<h2>Hello, you have called getData</h2>";
// }
// btn.addEventListener("click",getData)

const promise1=new Promise((resolve,reject)=>
{
    let a=12;
    if(a>10){
        resolve({name:"Rahul",branch:"AIMLB"});
    }
    else{
        reject("Rejected");
    }
}
);
promise1.then((msg)=>console.log(msg))
.catch(error=>console.log(error));